HNGi7 task 2
jgodstime/team-fury-1 pull request #215
Opened 2020-06-04 17:37 UTC by sammyebinne

2020-06-04 18:23 UTC, thebolarin requested changes
We need just one file in the scripts folder

2020-06-04 18:59 UTC, sammyebinne commented
Done

2020-06-05 09:55 UTC, sammyebinne reviewed
Thank you. Changes effected

2020-06-05 11:25 UTC, sammyebinne reviewed
mxzc

2020-06-05 14:22 UTC, closed without merging